### ISSUE TITLE
PDO Problem w/ basic example

### ISSUE THREAD

**Issue by vegbrasil** [kronusme/dota2-api#115]
Hi, I'm having a issue with this lib.

Using the following code:

```
<?php
require_once 'vendor/autoload.php';
use Dota2Api\Api;

Api::init('STEAM_API_KEY', array('MYSQL_SERVER', 'MYSQL_USER', 'MYSQL_PASS', 'MYSQL_DATABASE', 'MYSQL_PREFIX'));

$mm = new Dota2Api\Mappers\MatchMapperWeb(121995119);
$match = $mm->load();
$saver = new Dota2Api\Mappers\MatchMapperDb();
$saver->save($match);
?>
```
Returns:
```
Fatal error: Uncaught Error: Call to a member function prepare() on null in /var/www/vendor/kronusme/dota2-api/includes/Utils/Db.php:174 
Stack trace: #0 /var/www/vendor/kronusme/dota2-api/includes/Utils/Db.php(197): Dota2Api\Utils\Db->_queryPDO('SELECT match_id...', Array) 
#1 /var/www/vendor/kronusme/dota2-api/includes/Mappers/MatchMapperDb.php(269): Dota2Api\Utils\Db->queryFirstPDO('SELECT match_id...', Array) 
#2 /var/www/vendor/kronusme/dota2-api/includes/Mappers/MatchMapperDb.php(115): Dota2Api\Mappers\MatchMapperDb::matchExists('121995119') 
#3 /var/www/dota2.php(36): Dota2Api\Mappers\MatchMapperDb->save(Object(Dota2Api\Models\Match)) 
#4 {main} thrown in /var/www/vendor/kronusme/dota2-api/includes/Utils/Db.php on line 174
```

Can I get any help? I installed the *.sql and the match loads correctly, the database part that is not working.

Thanks a lot!

Edit: Forgot to mention, running PHP 7.0.0, MySQL 5.7.12.

**Comment by kronusme** [comment]
Hi, @vegbrasil. Are you sure, you put correct db settings (login, pass, db_name)?
I have test for MatchMapperDb that saves match to the db and it passed on the latest builds.

**Comment by vegbrasil** [comment]
Thanks for the fast answer, @kronusme!

Turns out my MySQL user table was corrupted, so everything was a mess. I'm really sorry!

Its now working great :+1: 


Thanks a lot!
